### ISSUE TITLE
{{outlet}} nested within {{#liquid-with}} not working

### ISSUE THREAD

**Issue by RickCSong** [ember-animation/liquid-fire#112]
Outlets inside of a {{liquid-with}} don't seem to be rendered :(  

Right now, my workaround is keeping it outside of the liquid-with and animating it separately... but I felt this was a bit unintuitive?

https://gist.github.com/RickCSong/e6f2613504ae2557aefc

**Comment by drewcovi** [comment]
I'm still running into this, wherein the outlets are pretty much empty.  I'm also running Fixtures though so that may play a part (I've tried to add latency to see if that would help).

**Comment by ef4** [comment]
Please see if you can produce a simple test case showing the behavior.
