### ISSUE TITLE
Possible conflict with Bootstrap modal

### ISSUE THREAD

**Issue by bkCDL** [ember-animation/liquid-fire#120]
I just started using liquid-fire in my ember app, mainly for the transitions, and I like it a lot. 

My app already had a number of Twitter Bootstrap (3) generated modals in it. Now when activated, my bootstrap modal objects only appear behind its modal background, whereas if I revert my {{liquid-outlet}} to {{outlet}}, it behaves normally with the modal object appearing in the foreground.

Are these two libraries in conflict with each other or have been tested together much?

To save myself time, the easiest solution would be to somehow disable liquid-fire's modal functionality, but I'm willing to convert my bootstrap modals to liquid-fire modals if that's the only way for them to work together.

FYI, I'm using liquid-fire the "old-school" way, though I hope to convert the app to ember-cli sometime in the next 6 months.

Bryan

**Comment by abhilashlr** [comment]
@ef4, @bkCDL 
a) I guess higher z-index will not solve the issue here.
b) The reason being, position: fixed behaves different when the parent has a transform property set in CSS. {{liquid-outlet}} uses transform for animating between routes and I guess the bootstrap modals are inside liquid-outlet.

REF: http://stackoverflow.com/a/2637267

**Comment by davidsteinberger** [comment]
@bkCDL I think the issue could be the liquid-container transform attribute. You could try to set it to _initial_ before invoking the bootstrap modal and restore it after dismissing the modal.
Something like:

      this.$().parents('.liquid-container').css({
        transform: 'initial'
      });
      this.$('.modal').modal();
      this.$('.modal').on('hidden.bs.modal', () => {
        this.$().parents('.liquid-container').css({
          transform: 'translateY(0)'
        });
       ...
    });

**Comment by fatihakkoyun** [comment]
use  ember-wormhole to avoid this situation


```
{{#ember-wormhole to="ember-wormhole-container"}}
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog">
     <div class="modal-dialog">
         .........................
     </div>
  </div>
{{/ember-wormhole}}
```

**Comment by trestini** [comment]
Just for clarification, use of ember wormhole should fix this situation. However, at least for ember rookies like me, it was not clear only by the @fatihakkoyun comment. Here's some step-by-step:

1. create a `div` and put some id on that (eg: `my-container`). This `div` MUST be created outside of `{{liquid-outlet}}` helper. An example could be:

```
  <div id="my-container"></div>
  {{liquid-outlet}}
```
 
2. use ember-wormhole as indicated by @fatihakkoyun, changing the `to` attribute with the name of the container that you've created. The value of `to` attribute will be prepended with a "#" char to be transformed in a selector, so, use only the name of the container, not it's selector.
