### ISSUE TITLE
Support for Ember 1.9.0 + HBS 2.0.0?

### ISSUE THREAD

**Issue by oskarrough** [ember-animation/liquid-fire#146]
Hi, I tried to update my app to Ember 1.9.0 and Handlebars 2.0.0. I'm on ember-cli 0.1.4. With a single {{liquid-outlet}} in my template, I get the following deprecation:

`DEPRECATION: Using {{outlet}} with an unquoted name is not supported.`

But the outlet doesn't use a name in this case, so? Apologies if this was already fixed in the master branch.

**Comment by mattgrannary** [comment]
Same here. I'm using 0.16.0 but still get the depreciation message.

**Comment by cball** [comment]
In case anyone stumbles on this deprecation that happens to be using emblem for templates, you need to use a standard handlebars tag:

`| {{liquid-outlet}}`
