### ISSUE TITLE
Debug logging

### ISSUE THREAD

**Issue by ef4** [ember-animation/liquid-fire#147]
We should offer optional debug logging so people can trace both the rule-matching process and the running of a transition itself.

**Comment by mphasize** [comment]
:+1:

**Comment by jbrown** [comment]
:+1:

**Comment by ef4** [comment]
This is actually already done on master. Just needs to get documented.

**Comment by lukemelia** [comment]
Related: #225

**Comment by chundabear** [comment]
The related issue was merged and documentation exist now. unless this issue is open for a reason. http://ember-animation.github.io/liquid-fire/#/transition-map/debugging-constraints

**Comment by ef4** [comment]
Thanks, good catch.
