### ISSUE TITLE
Is there a way to match all routes

### ISSUE THREAD

**Issue by jrdn91** [ember-animation/liquid-fire#149]
I tried doing this

```
this.transition(
    this.fromRoute('*'),
    this.toRoute('index'),
    this.use('crossFade')
  );
```

and it didn't work, is there a way to match when any route transitions to the index route like this?

**Comment by marcemira** [comment]
Hello is there a way to match all routes, not just the ones that reaches index from anywhere.. something like:

**Comment by ef4** [comment]
If you don't want to limit to particular routes, just make a rule that doesn't constrain the routes. fromRoute and toRoute are optional constraints.

If you have a single liquid-outlet that should always fade, just put `use="fade"` directly on it.

**Comment by ylligashi** [comment]
This

`this.transition(
  this.toRoute('*'),
  this.use('fade')
);`

does not work for me. Any clue

**Comment by ef4** [comment]
`toRoute` is a constraint -- if you don't include a constraint, your transition rule will always match. So just say:

```js
this.transition( this.use('fade') );
```

Alternatively, you can do `{{liquid-outlet use="fade"}}` to make a particular liquid-outlet always use that animation.
