### ISSUE TITLE
Matching based on a route's dynamic segment

### ISSUE THREAD

**Issue by pogopaule** [ember-animation/liquid-fire#15]
It would be great if the transitions could also match a route's dynamic segment, so that one could express something like the following:

router.js

```
Router.map(function() {
  this.resource('foo', { path: '/foo/:bar' });
});
```

transitions.js

```
export default function() {
  this.transition(
    this.route(function(fromRoute, fromParams, toRoute, toParams) {
      return parseInt(fromParams.bar) > parseInt(toParams.bar);
    }),
    this.use('toLeft')
  );

  this.transition(
    this.route(function(fromRoute, fromParams, toRoute, toParams) {
      return parseInt(fromParams.bar) < parseInt(toParams.bar);
    }),
    this.use('toRight')
  );
}
```

Example: transition from route `http://localhost:4200/foo/42` to `http://localhost:4200/foo/41` would use animation `toLeft` and a transition from `http://localhost:4200/foo/42` to `http://localhost:4200/foo/43` would us animation `toRight`

I am not sure how to extend the DSL properly. The code above is not really a proposal for the DSL...

I had a quick look at the code to see if I can implement this feature, but felt that this is not so easy because the there is only the "fromView" and the "toView" (https://github.com/ef4/liquid-fire/blob/master/app-addon/views/liquid-outlet.js#L44). So there is no information about the route or its dynamic segment. Is that correct?

**Comment by cwarny** [comment]
I can't seem to get this to work. Has there been a change in API? I see that now `fromModel`and `toModel` take two arguments, but I still keep getting `undefined` for both arguments. Note that I'm trying to capture a change in model when the dynamic segment of the route changes.

```
// app/router.js

Router.map(function() {
	this.route("campaigns", { path: "/" }, function() {
		this.route("campaign", { path: "/campaign/:election_year" });
	});
});
```

Trying to capture changes from `/campaign/2008` to `/campaign/2012` (for instance).

My `transitions.js` file is as follows:

```
// app/transitions.js

export default function() {
	this.transition(
		this.toModel(function(newModel, oldModel) {
			return oldModel && newModel && oldModel.get("election_year") > newModel.get("election_year");
		}),
		this.use("to-left")
	);
    this.transition(
		this.toModel(function(newModel, oldModel) {
			return oldModel && newModel && oldModel.get("election_year") < newModel.get("election_year");
		}),
		this.use("to-right")
	);
});
```

And finally my template uses a `{{liquid-outlet}}`:

```
{{!-- app/templates/campaigns.hbs --}}

{{liquid-outlet}}
```

Any clues as to what I'm doing wrong?

**Comment by ef4** [comment]
liquid-outlet does not handle model-to-model transitions on the same route. This is a deliberate decision to deal with the fact that Ember uses singleton controllers, so the old and new views are backed by the same controller, so we cannot easily fork the state and show them side-by-side.

You can animate model-to-model transitions via liquid-with.

**Comment by cwarny** [comment]
Thanks, that helps. I'm still a little confused as to whether `{{liquid-with}}` can handle my specific use case (it needs to be aware of the "direction" of the change, i.e. whether `election_year` increases or decreases). I would think is a common pattern. I posted [this question](http://stackoverflow.com/questions/30716394/direction-aware-transition-with-ember-liquid-fires-liquid-with-helper) on StackOverflow if you have the opportunity to take a look.

**Comment by ddemolina** [comment]
Hi,
I have a similar question but in my case when i'm triying to go from content/1 to content/2 a loading substate is shown between them. I need to know if I'm going from 1 to 2 ( or 2 to 1)  when I'm going to enter in the loading substate
