### ISSUE TITLE
helpers lose access to keywords

### ISSUE THREAD

**Issue by raycohen** [ember-animation/liquid-fire#167]
I ran into this when trying to convert the non-keyword form of {{#each}} in my project to {{#each item in list}} syntax

I added the following to the dummy app for this project (and defined myItems in the application controller) and saw the same behavior: 

```
    {{#each item in myItems}}
      <li>
        This shows: {{item.name}}

        {{#liquid-unless item.isHidden}}
          This does not: {{item.name}}
        {{/liquid-unless}}
      </li>
    {{/each}}
```

**Comment by ef4** [comment]
Thanks for the bug report, which Ember version are you using?

**Comment by raycohen** [comment]
I encountered it in our code, running ember 1.9.1.  Tried updating to ember canary and got the same behavior.  I then tried it in the dummy app inside this project, which is 1.8.1

**Comment by chrislopresto** [comment]
@raycohen and I just updated our app to ember 1.11.0-beta.5 and a [recent commit on liquid-fire master](https://github.com/ef4/liquid-fire/commit/c622e455cbe17444af668b6405c1fd497b52ac04) and this now appears to be working.

**Comment by winne42** [comment]
if this has been fixed 5 years ago, maybe this issue can be closed?
