### ISSUE TITLE
Animation performance for transitioning routes

### ISSUE THREAD

**Issue by Globegitter** [ember-animation/liquid-fire#17]
It seems if you have quite complex websites and you animate the whole route transition (i.e. the entire site), the animation is quite visibly 'laggy'.
Do you have any ideas if and how performance cold be improved? Does this mostly have to do with velocity? Or is that something rather with the implementation in liquid-fire?

If an example would help I would be happy to provide one.

Oh and my code is as simple as:

``` js
export default function(){
  this.transition(
    this.fromRoute('form.index'),
    this.toRoute('form.impact'),
    this.use('toLeft')
  );

  this.transition(
    this.fromRoute('form.impact'),
    this.toRoute('form.index'),
    this.use('toRight')
  );
}
```

and using a `liquid-outlet` in my `form.hbs`

**Comment by runspired** [comment]
I bump into this a lot with all sorts of content (not just images) and the problem is that there doesn't seem to be a good way to trigger or delay the processing of some methods on the incoming route until after the animation is complete.
