### ISSUE TITLE
Bootstrap Modal

### ISSUE THREAD

**Issue by knownasilya** [ember-animation/liquid-fire#217]
So I've yet to get a good configuration for styling the modal like the bootstrap one, especially the layout portion.

Has anyone gotten the bootstrap modal to work with liquid-fire's modal (just the markup/styles, not the bootstrap.js)?

**Comment by Andersonlimahw** [comment]
I'm using liquid-fire, and having conflict with bootstrap modal, its don't work ?

**Comment by knownasilya** [comment]
I created https://github.com/knownasilya/bootstrap-modal

**Comment by Andersonlimahw** [comment]
cant i , use the native bootstrap modal ? , a haved conflit in other projects using bootstrap-modal

**Comment by knownasilya** [comment]
You can, it should mainly just work, but applying animations is a different story.

**Comment by Andersonlimahw** [comment]
understand man , tnk's for the answer, and sorry was another addon than i haved conflict .

**Comment by knownasilya** [comment]
What's the error?

**Comment by Andersonlimahw** [comment]
in console, don't show any error.

i changed the default modal , to modal of ember-bootstrap , and resolved it ;

tank's again :+1:
