### ISSUE TITLE
Prebuilt releases

### ISSUE THREAD

**Issue by mike183** [ember-animation/liquid-fire#237]
The 0.19.x releases don't appear to have prebuilt versions available. Are they no longer being supported?

I tried building the files using the instructions [here](https://github.com/ef4/liquid-fire/blob/master/packaging/README-packaging.md), but the resulting JS file was outputting the following error in Chrome's console.

`Uncaught SyntaxError: Unexpected token )`

The error seems to be being caused by line 261, which looks like some ES6 syntax that hasn't been transpiled.

```
259: decrementRunningTransitions: function() {
260:   this.activeCount--;
261:   Ember.run.next(() => {
262:     this._maybeResolveIdle();
263:   });
264: },
```

**Comment by ef4** [comment]
Yes, this needs work. Rather than try to hack on a liquid-fire specific solution, I hope we can make a tool that uses ember-cli to make a standalone package of any ember addon.

**Comment by ef4** [comment]
I just released a new tool that can build liquid-fire (and hopefully every other addon!) for use by non-ember-cli apps: https://github.com/ef4/ember-giftwrap

**Comment by ef4** [comment]
I also updated [this example](https://github.com/ef4/liquid-fire/blob/master/example/prebuilt-example.html) to show how you would use the output from giftwrap.

**Comment by mike183** [comment]
Awesome! Managed to get this working perfectly once I'd seen that you had submitted a pull request to ember-cli with some patches.
