### ISSUE TITLE
How to use liquid-bind to make transitions between components?

### ISSUE THREAD

**Issue by Dfmarulanda** [ember-animation/liquid-fire#314]
Hi. 
Im new to liquid-fire. I manage to made some transitions with if clause. Im now trying to make some transitions between 3 components. I just cant understand how can i do it. 
Do you have some example?

**Comment by Eptis** [comment]
This will probably help:
http://ef4.github.io/liquid-fire/#/transition-map/dom-constraints
http://ef4.github.io/liquid-fire/#/transitions/defining

**Comment by ef4** [comment]
Here's one idea:

```handlebars
{{#liquid-with activeComponentName as |currentActiveComponentName|}}
  {{component currentActiveComponentName}}
{{/liquid-with}}
```

**Comment by denzo** [comment]
`liquid-with` no longer exists. Use `liquid-bind`
