### ISSUE TITLE
Dynamic outlet name not working in 0.20.x

### ISSUE THREAD

**Issue by rwjblue** [ember-animation/liquid-fire#319]
I have been updating a library to 0.20 (from 0.19), and have come across a potential bug in `{{liquid-outlet}}` with dynamic outlet names.  Specifically [app/components/liquid-outlet.js#L7](https://github.com/ef4/liquid-fire/blob/master/app/components/liquid-outlet.js#L7) uses `this.attrs.inputOutletName` but when invoked with `{{liquid-outlet someCP}}` the value present in `this.attrs.inputOutletName` will be a mutable object (and not the plain string result of the CP). Changing to `this.get('inputOutletName')` or `this.getAttr('inputOutletName')` would fix the issue I believe.

In the meantime, using `{{liquid-outlet (readonly someCP)}}` fixes my app issue.

---

As an aside: the update to 0.20 has been mostly painless, thank you for working so hard on this!

**Comment by winne42** [comment]
@ef4 This seems to have been fixed in https://github.com/ember-animation/liquid-fire/commit/99cdbde032c458d069f078efaa2ab05d4e48ca2f#diff-84442a6e73fc694421b14c70b0ed26ed
Can this issue be closed?
