### ISSUE TITLE
liquid-fire outlet breaks ember-cloaking

### ISSUE THREAD

**Issue by abarax** [ember-animation/liquid-fire#38]
Using a 'liquid-outlet' with a 'cloaked-collection' breaks the cloaked collection.  Essentially once you start scrolling the subviews disappear or "cloak" and do not uncloak.

Any ideas as to why this might be happening? I am still investigating the cause there does not seem to be any exceptions thrown at all.

**Comment by runspired** [comment]
@abarax I use the two together (and I maintain the es6 branch of cloaking).  The only conflict I've discovered comes when using a liquid-fire animation with vertical movement, at the moment when cloaking is determining what is on screen, nothing is.  My solution is to fire a fake scroll event in afterRender.
