### ISSUE TITLE
isDevelopingAddon is mistakenly turned on in npm v0.21.3

### ISSUE THREAD

**Issue by justin-lau** [ember-animation/liquid-fire#383]
It triggers eslint in parent project when set to true as described in jonathanKingston/ember-cli-eslint#14. And that option is supposed to be turned on in development only.

**Comment by justin-lau** [comment]
I found the following lines appears only on npm repository when I install with `npm install liquid-fire`:

```js
// index.js
isDevelopingAddon: function() {
    return true;
},
```

but not on the github repository if I install with `npm install ef4/liquid-fire#v0.21.3`

**Comment by runspired** [comment]
I've fallen victim to this too recently, `npm publish` pulls your current branch and state, including uncommitted changes.  I usually have it set to `true` and stash when releasing, if I haven't stashed it shows up in `npm`.

**Comment by justin-lau** [comment]
I have fallen before too. I now write pre-publish scripts npm my `package.json` to lint and test everything before actually uploading to npm. Similar tricks can be applied to prevent this from happening again =)

**Comment by ef4** [comment]
Thanks, this explains some otherwise confusing bug reports lately.

**Comment by brzpegasus** [comment]
@ef4 Do you plan on publishing a new version to npm anytime soon? This is also causing any projects that use both `liquid-fire` and `ember-suave` to get a bunch of warnings/failing tests because `ember-suave` ends up linting the `liquid-fire` modules as a result of `isDevelopingAddon` being `true`.

**Comment by runspired** [comment]
@brzpegasus you could probably install directly from the github tag instead of npm and avoid the issue for now.

**Comment by winne42** [comment]
@ef4 I suppose this issue has been fixed in every version since? So this issue could be closed? Thanks!
