### ISSUE TITLE
Issue using liquid-spacer inside flex box

### ISSUE THREAD

**Issue by rox163** [ember-animation/liquid-fire#392]
I have a liquid-spacer being used to animate height changes of rows in a list based on a button click. The outer container is flex-box. So the width should be flexible and adjust based on window sizing. My problem is that when resizing the window, the row width stays the same and instead of being responsive, content gets cut off. The spacer div seems to have the width style set on it when the page loads. Then this width does not change on window resizing. 
```
 {{#liquid-spacer }}
		{{list-item model=record}}
{{/liquid-spacer}}
```

This is the  div put in by the spacer - 
`<div id="ember650" class="ember-view" style="overflow: hidden; width: 815px; height: 50px;"><div id="ember657" class="ember-view" style="overflow: auto;">`

How can I get the rows to be responsive in width ?

**Comment by mschinis** [comment]
Having issues resizing the width in my responsive website as well, but I don't use flex box.

**Comment by ktrhn** [comment]
I guess an option to specify that only height should be handled by liquid-spacer could be helpful. The current fixed setting of width breaks responsive layouts.
