### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stream' of undefined

### ISSUE THREAD

**Issue by jackmatt2** [ember-animation/liquid-fire#396]
ember@2.2.0
liquid-fire@0.21.3

I Have just updated to ember 1.13.x to 2.2.0 and anywhere I have a `{{liquid-outlet}}` I get the following error:

```
Uncaught TypeError: Cannot read property 'stream' of undefined
```

Changing `{{liquid-outlet}}` back to `{{outlet}}` fixes the issue.

**Comment by mrinterweb** [comment]
I was just running into the same issue. I was able to get things working again with liquid-fire 0.22.1.

**Comment by SirZach** [comment]
upgrading to `0.23.0` did the trick for me when i was encountering this issue
