### ISSUE TITLE
Transitions should have access to the "to" and "from" routeName

### ISSUE THREAD

**Issue by kybishop** [ember-animation/liquid-fire#414]
This would allow route-specific transitions, such as remember scroll position in a route's deactivate hook (via a global variable), then recalling that scroll position when returning to that route.

**Comment by ef4** [comment]
Transitions have access to the old and new values, although that is a more general concept that just route names, and in the case of routes the `value` is actually a data structure representing the route, so the API can use some clarification.

From within a running transition, see `this.oldValue`, `this.newValue`, and `this.older` (which is a list of any older states when multiple transitions have fired before the earliest has finished).

The public API for what is available on `this` in a transition is all defined here:

https://github.com/ef4/liquid-fire/blob/b5a226c6edd51c27135f26b3a5e40b825e4d9fa9/addon/running-transition.js#L42-L79
