### ISSUE TITLE
Reverse explode for liquid-modal?

### ISSUE THREAD

**Issue by craigsketchley** [ember-animation/liquid-fire#416]
First off, great library. Thanks.

Is doing a reverse animation for explode supported? I am trying to do it for a `liquid-modal`.

Here's what I've got for my modal transition but it's not doing the `reverse`:

```
this.transition(
  this.inHelper('liquid-modal'),
  this.use('explode', {
    pick: '.lf-overlay',
    use: ['fade', {maxOpacity: 0.5, duration: 200}]
  }, {
    pick: '.lm-container',
    use: ['toUp', {delay: 250, duration: 500, easing: 'ease-in-out'}]
  }),
  this.reverse('explode', {
    pick: '.lm-container',
    use: ['toDown', {duration: 500, easing: 'ease-in-out'}]
  }, {
    pick: '.lf-overlay',
    use: ['fade', {delay: 500, maxOpacity: 0.5, duration: 200}]
  })
);
```

Am I missing something?

**Comment by ef4** [comment]
Hello and thanks.

Yes, reverse is supported. But it works by reversing the constraints in the rule, and your rule has no constraints to reverse (just `inHelper`, which isn't reversible).

Try add `toValue(true)`, which will make the rule only match when it's transitioning into a modal. Then the reverse will only match when transitioning out.
