### ISSUE TITLE
Interactive documentation site link is broken

### ISSUE THREAD

**Issue by jagthedrummer** [ember-animation/liquid-fire#418]
The link in the README points to http://ef4.github.io/liquid-fire, but that's coming up as "Site not found - GitHub Pages". Has the site moved?

**Comment by runspired** [comment]
Thanks! We're doing a bit of reshuffling, a few links did break in the process.  I'm surprised github doesn't preserve the gh-pages link given that it preserves the repo link.

@ef4 we might want to see if there's a way to leave a site at the old url too.

**Comment by snostorm** [comment]
For now maybe hard-code to http://ember-animation.github.io/liquid-fire/ ?

**Comment by kiwiupover** [comment]
#419 fixes this issue
