### ISSUE TITLE
No animation between routes with the same template

### ISSUE THREAD

**Issue by Baukereg** [ember-animation/liquid-fire#424]
I have two routes with transition animations using Liquid Fire. Works fine!
But since both route templates are identical, I created one generic template and applied them to both routes using renderTemplate. Works fine as well, but sadly breaks the animation.

I quess Liquid Fire doesn't really animate between routes but between templates instead.

**Comment by Cryrivers** [comment]
this is mentioned before. you should use `liquid-bind` instead of `liquid-outlet` in your case.

**Comment by ef4** [comment]
I think two issues are being slightly confused.

Model-to-model transitions on a single route definitely require `liquid-bind` instead of `liquid-outlet`.

But @Baukereg's original bug report is different, and likely a duplicate of https://github.com/ember-animation/liquid-fire/issues/18
