### ISSUE TITLE
liquid fire transitions not working

### ISSUE THREAD

**Issue by Sureshowler** [ember-animation/liquid-fire#436]
{{#liquid-if}} shows no error...but it behaves simple...the transitions applied in transitions.js under app directory are not taken.... i am using latest ember and liquid fire

**Comment by ef4** [comment]
Try enabling debug logging for your transition rule:

http://ember-animation.github.io/liquid-fire/#/transition-map/debugging-constraints

**Comment by Sureshowler** [comment]
i enabled debug logging...
export default function(){
	var duration=500;
this.transition(
this.fromRoute('test1'),
this.toRoute('test'),
this.use('crossFade',{duration}),
this.reverse('crossFade',{duration}),
this.debug()
);
}

**Comment by Sureshowler** [comment]
I tried inline and the transitions are working now... but the transitions given in transitions.js are not working

**Comment by ef4** [comment]
Double check the filename is `app/transitions.js`. If it's being run at all you should see some debug output in the browser console (not terminal).

**Comment by Sureshowler** [comment]
thanks ... it works fine... transitions.js was under ember project... i moved it under app...
