### ISSUE TITLE
Way to animate between routes without link-to

### ISSUE THREAD

**Issue by netes** [ember-animation/liquid-fire#443]
Hi,
At first, thanks for the great addon :)
I'm wondering if there is a way to trigger animation between routes if I'm not using `link-to`. I need to transition using `transitionToRoute` in controller but this doesn't trigger animation.

Cheers.

**Comment by ef4** [comment]
liquid-fire doesn't care how you trigger a transition. It works the same with `transitionToRoute`. So you must have something else causing your animation to not run.

**Comment by netes** [comment]
You're right. In one particular template I forgot to change `{{outlet}}` to `{{liquid-outlet}}`... :speak_no_evil: Anyway - thanks for fast reply, all in all it was helpful :smile:
