### ISSUE TITLE
Dismiss modal with "replace" rather than "transition"

### ISSUE THREAD

**Issue by whodies** [ember-animation/liquid-fire#444]
Hi, 

I'm writing a mobile application and I need the back button to work consistently throughout. The standard ember link-to helper has a "replace" option in case I don't want to keep the last route in the browser history. Same goes for the "transition()" method. 

I can't find the same sort of functionality when dismissing modals. I want to make sure that if I hit the browser "back" button the modal doesn't pop back up after I've dismissed it.

Any suggestions ? 

Thanks

**Comment by ef4** [comment]
You could choose not to tie the modal to a query param at all, in which case it won't affect browser history.

Or you can [configure your query parameter to use replaceState](https://guides.emberjs.com/v2.4.0/routing/query-params/#toc_update-url-with-code-replacestate-code-instead).

**Comment by whodies** [comment]
I need the browser's history. Without it the mobile back button will not dismiss the modal the way it currently does. This is essential because there's no simple way for me to detect a mobile back button being clicked via javascript.
Obviosly there's an ember transition going on somewhere in the modal dismissal code. All I need is to replace it wIth a "replace" transition. Can you point me to where it's at ?

**Comment by ef4** [comment]
See the link I posted above, that allows you to configure the ember transition.

**Comment by whodies** [comment]
That's a very cool thing to know about query params, but it still doesn't solve the issue. 
I need to use a regular transition when I'm opening a modal and then a replaceState transition when closing it. 
Most apps used today close their popups with the mobile "Back" button (amongst other ways). The back button is essentially a history.back() function. If I don't put the modal in the history when I open it, I can't close it by using the back button. 
Rather than nullifying the query param, I need to be able to change the transition triggered by the modal's built in "dismiss" action. 
Sorry I didn't react to the link you posted earlier (I admit I skimmed a little). Now that I have though, I'd like to reiterate my request: Can you point me to the place in your code where the dismiss action triggers the transition ?
Thanks for the prompt replies, and your truelly awesome plugin

**Comment by ef4** [comment]
liquid-fire _doesn't_ trigger the transition. When dismissing a liquid-modal, all it does is set your params back to their default values. If you've bound them to the URL, that will cause a transition however you've configured. But you could also just observe them and do something custom.

**Comment by jhilden** [comment]
We have the same issue that we want users to be able to dismiss/close the current modal by using the back button, but we don't want the modal to reappear when the user hits the back button after the modal has been closed.

@whodies did you end up finding a solution?

**Comment by whodies** [comment]
I did actually. Just make sure that the ember link tag that goes backwards (i.e the "close" or "back" button) has the param  replace=true in it. That way going back actually replaces the current browsing history queue item rather than adding to it.

**Comment by jhilden** [comment]
@whodies thanks a lot for the quick and helpful response.

I'm wondering though, this only works when the user closes the modal using a button/link and not when the modal is closed using other methods (e.g. escape key, back button, or clicking outside the modal).  Is that correct?  Does anybody have any further thoughts on this?

**Comment by jhilden** [comment]
> not when the modal is closed using other methods (e.g. escape key, back button, or clicking outside the modal)

Actually, I tried it again and closing the modal using the back button will not reopen the modal on a subsequent back button click on the underlying page, since we went back one state in the history.  So this only happens when closing the modal through one of the other means (link without `replace=true`, escape key, outside click).

@ef4 could it be an option to just always trigger a `window.history.back()` when closing a modal that is controlled by a param that is bound to the URL?  If that param is bound to the URL it will be implicitly reset by going back to the previous URL anyways.  Is there be any clean way to hook into the `dismiss` action?

**Comment by whodies** [comment]
Yup, Inside the component modal actions add:
`dismiss:function(){
	window.history.back();
}`
Worked for me :)

**Comment by jhilden** [comment]
For some reason just adding a `dismiss` function to my actions didn't work for me, but I did the code below worked well for me:

```
_customDismiss() {
  window.history.back();
 },

actions: {
  close() {
    this._customDismiss();
  },
  outsideClick() {
    this._customDismiss();
  },
  escape() {
     this._customDismiss();
  }
}
```
