### ISSUE TITLE
Route doesn't transition on reverse with materialize cards in view

### ISSUE THREAD

**Issue by eddieduro** [ember-animation/liquid-fire#446]
Here is my transitions.js file 
`export default function(){
  this.transition(
    this.fromRoute('index'),
    this.toRoute('post'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
}
`
my route
 `Router.map(function() {
  this.route('post', {path: '/post/:post_id'});
});
`

I am currently using ember-cli-materialize as a quick proto navabar. I can transition from the index to the post page the 1st time no issue. But when I transition from the post page to the index page for the second time both pages display at once.

**Comment by eddieduro** [comment]
Seems to be having an issue because I am using materialize's cards in my transition.

**Comment by eddieduro** [comment]
found problem - if anyone runs into this issue it seems you cannot have an id on your md-card
`{{#each post as |post|}}
  {{#md-card id='card'}}
    {{#md-card-content}}
      <h3>{{post.title}}</h3>
      <h4>By, {{post.author}}</h4>
    {{/md-card-content}}
    {{#md-card-action}}
      {{#link-to 'post' post.id}}<span class='purple-text'>View the question</span>{{/link-to}}
    {{/md-card-action}}
  {{/md-card}}
{{/each}}`

returns this error in the chromes debugger 

> Exception was thrown by user callback. Error: Assertion Failed: Attempted to register a view with an id already in use: card

so once I removed the id from the md-card everything went worked perfectly.

**Comment by ef4** [comment]
This is a general problem with IDs and animation.

If you want to animate two different states of your UI simultaneously, it means both copies will be in DOM at the same time. So any IDs present will get duplicated. Ember's event system will complain about the duplicate IDs because it can't safely route events unambiguously.
