### ISSUE TITLE
Slide up / Slide down on a fade

### ISSUE THREAD

**Issue by jpoiri** [ember-animation/liquid-fire#450]
I have a ember template with 2 sections, where one taller section is visible by default and other smaller one is hidden until I hit a button.

I am using liquid-fire, most specifically the liquid-if helper to do a simple fade in / fade out of the 2 sections. This works however there is a slide up / slide down based on DOM position that occurs between toggling the 2. Is there a way to prevent this behavior

Here's sample how template looks like:

     {{#liquid-if isPasswordResetLinkConfirmVisible class="lf-fade"}}
        <h1 class="text-center">{{t 'reset_password.text.resend_email_header'}}</h1>
        <p class="text-center">
            {{t 'reset_password.text.resend_email_line_1'}}<br/>
            {{t 'reset_password.text.resend_email_line_2'}}
            <i class="fa fa-envelope-o email-icon"></i>
        </p>
    {{/liquid-if}}

    {{#liquid-if isPasswordResetLinkVisible class="lf-fade"}}
        <h1 class="text-center">{{t 'reset_password.text.expired_header'}}</h1>
        <p class="text-center">
            {{t 'reset_password.text.expired_line_1'}}<br/>
            {{t 'reset_password.text.expired_line_2'}}
        </p>
        {{mx-button action=(action "sendNewPasswordResetLink") size="large" label=(t 'action.send_new_link') block=true}}
    {{/liquid-if}}

Here a sample of my transition:

```
this.transition(
    this.hasClass('lf-fade'),
    this.toValue(true),
    this.use('fade', {
        duration: 600
    })
);
```

**Comment by kiwiupover** [comment]
@jpoiri I posted an answer on stackoverflow [here](http://stackoverflow.com/questions/36889862/fade-in-fade-out-in-liquid-fire/36893557#36893557) 

You can close this.
