### ISSUE TITLE
liquid-bind transition not working

### ISSUE THREAD

**Issue by ajainvivek** [ember-animation/liquid-fire#451]
I am trying to render component dynamically with slide up transition 

**HBS File**
```
{{#each widgets as |widget|}}
  {{#liquid-bind widget class="progressive-loader" as |card|}}
    {{#component card.name}}
      {{card.data}}
    {{/component}}
  {{/liquid-bind}}
{{/each}}
```

**Transition File**
```
this.transition(
    this.hasClass('progressive-loader'),
    this.use('toUp', {duration: 3000}),
    this.debug()
  );
```

I get error on console **[liquid-fire rule 7] rejected because firstTime was yes**

I am not sure what I am doing wrong

**Comment by ef4** [comment]
If you really want it to animate at initial render, you can explicitly opt in: http://ember-animation.github.io/liquid-fire/#/transition-map/initial-constraints

**Comment by ajainvivek** [comment]
@ef4 Thanks :) It works perfect 👍
