### ISSUE TITLE
Ember 2.0 support

### ISSUE THREAD

**Issue by CostaRico** [ember-animation/liquid-fire#452]
Using {{view}} or any path based on it (application/templates/components/liquid-modal.hbs

**Comment by alkamin** [comment]
I ran into this as well and it turns out that `ember install liquid-fire` installed liquid-fire@0.19.6.

I changed the version in my `package.json` to 0.23.0 to match the latest version, `npm install`ed and the problem was resolved.

So this seems like an npm publishing issue.

**Comment by CostaRico** [comment]
@alkamin thx u a lot!

**Comment by acorncom** [comment]
Looks like this issue can be closed?

**Comment by CostaRico** [comment]
@acorncom yep, thx!

**Comment by acorncom** [comment]
@CostaRico Would you mind closing it, I can't? 😀
