### ISSUE TITLE
`Introduction to liquid-fire` on The Ember Show

### ISSUE THREAD

**Issue by taras** [ember-animation/liquid-fire#457]
Would you someone familiar with this library be interested in giving a lightning talk about this addon on The Ember Show? We're recording the next episode on June 11th followed by July 2nd. 

An introduction to <addon> talk is about 15 minutes long and covers the following:
- Why was this addon created?
- When should it be used?
- How does one get started?
- What should the person be aware of?

You can see some of the previously recorded introduction talks on [Global Ember Meetup Videos](https://www.embermeetup.com/videos?category=addon-introductions) page.

Would you be able to give this talk?

**Comment by ef4** [comment]
I'm pinging @taras directly to schedule this.
