### ISSUE TITLE
liquid-if not being triggered

### ISSUE THREAD

**Issue by kgish** [ember-animation/liquid-fire#461]
I'm trying to use a `{{#liquid-if}}` to animate certain skills which are made visible depending on whether or not the `display` attribute is set to true.

The `display` will be true if the score matches the filter value otherwise it'll be false, causing the item to disappear.

```
<div class="skills-list">
    {{#each model as |skill|}}
        {{#liquid-if skill.display class="skill-display"}}
            {{skill-item item=skill}}
        {{/liquid-if}}
    {{/each}}
</div>
```

In the `transition.js` file I have this:

```
var duration = 250;

this.transition(
    this.hasClass('skill-display'),
    this.toValue(true),
    this.use('crossFade', {duration}),
    this.reverse('toLeft', {duration})
);    
```

The list is filtered correctly and only the correct items are listed. However, no animations are being triggered, what might I be doing wrong?

**Comment by kgish** [comment]
I enabled debugging and this is what I see for all of the items:
```
[liquid-fire rule 1] rejected because firstTime was yes
[liquid-fire rule 1 reverse] rejected because firstTime was yes
```

**Comment by ef4** [comment]
If your `{{each}}` isn't stable, the `liquid-if` won't have a chance to animate because it will keep getting created and destroyed by the `{{each}}`.

So check that you are not changing the `model` list and add a stable `key=` if necessary to the `{{each}}`.

**Comment by kgish** [comment]
Not quite sure I understand you (stable `key=` ?), could you please elaborate?

**Comment by ef4** [comment]
http://emberjs.com/api/classes/Ember.Templates.helpers.html#toc_specifying-keys

**Comment by kgish** [comment]
Interesting, never heard of that. Gave it a try, but the following error is generated:
```
Uncaught Error: You must provide a string key when calling `yieldItem`; you provided undefined
```

**Comment by kgish** [comment]
I have a slight confession to make. Rather than using `model as |skill|` I am using `randomSkills as |skill|` which returns takes the model, shuffles it around and returns an randomized array of objects. Could this be what is going wrong.

**Comment by ef4** [comment]
That error message probably means you said `key=something` (referring to an undefined variable_ instead of `key="something"` (referring to a string).

The randomization could be the problem if it isn't stable. If it's a computed property that doesn't change while you're trying to animate, then it's OK.

**Comment by kgish** [comment]
Did provide a string in double-quotes.

**Comment by kgish** [comment]
If I replace `randomSkills` with `model` it works perfectly!

```
{{#each model as |skill|}}
    {{#liquid-if (or (eq filterScore 0) (eq skill.score filterScore)) class="skill-display"}}
        {{skill-item item=skill icons=(eq filterScore 0)}}
    {{/liquid-if}}
{{/each}}
```

However, how can I get it to work by randomizing the model skills?

**Comment by kgish** [comment]
Okay, I've now been struggling for a couple more hours and still cannot get it to work.

Any suggestions would be greatly appreciated, thanks alot in advance.

**Comment by ef4** [comment]
How do you compute `randomSkills`?

**Comment by kgish** [comment]
Feel free to have a look yourself.

https://github.com/kgish/gishtech.com/blob/master/app/components/skill-listing.js

**Comment by rwwagner90** [comment]
👋 I am doing some issue cleanup, and this issue seems pretty old, and not like a bug with liquid-fire. I am going to close it for now, but please feel free to reopen if you are experiencing the issue still!
