### ISSUE TITLE
liquid-modal breaks on context.view = this.innerView(context)

### ISSUE THREAD

**Issue by srowhani** [ember-animation/liquid-fire#467]
The following error is thrown when it hits the mentioned snippet:

```vendor.js:15955 Uncaught Error: Assertion Failed: You must use Ember.set() to set the `view` property (of <Ember.Object:ember785>) to `<>`.```

This can be fixed by changing `liquid-modal.js`, line 9 from:

`context.view = this.innerView(context)`

to this

`context.set('view', this.innerView(context))`

Thanks!

**Comment by sglanzer** [comment]
+1

**Comment by ef4** [comment]
Closing because liquid-modal no longer exists.
