### ISSUE TITLE
Liquid Fire Hero Transition

### ISSUE THREAD

**Issue by seanmhoffman** [ember-animation/liquid-fire#476]
Hello,

I was wondering if it was possible to implement a hero transition, like [this](https://github.com/DevAndyLee/Angular-Hero). Basically allowing you to carry an element or elements over to the next page during a page transition.

Thanks

**Comment by kiwiupover** [comment]
@seanmhoffman Here is a video talking about that sort of animation from ember conf 2015.
https://youtu.be/p8aF-7-_cE8?t=10m10s

**Comment by seanmhoffman** [comment]
@kiwiupover Thanks for the quick response, I'll check that out.

**Comment by acorncom** [comment]
Believe this issue can be closed ...
