### ISSUE TITLE
Prevent liquid-if content getting destroyed

### ISSUE THREAD

**Issue by mhluska** [ember-animation/liquid-fire#478]
I'm using the `liquid-if` component which seems to destroy its child DOM nodes when the if condition is not true. This is problematic for DOM nodes that take a long time to initialize like Facebook / Twitter share buttons. Is there a way to prevent them from being destroyed?

**Comment by ef4** [comment]
If you don't mind rendering both states simultaneously, you don't really need liquid-if. You can just toggle a class and use CSS transitions or animations directly.
