### ISSUE TITLE
Error Could not find module ember-htmlbars/keywords/view

### ISSUE THREAD

**Issue by vlascik** [ember-animation/liquid-fire#484]
Seems that liquid fire still requires `ember-htmlbars/keywords/view` from `addon/ember-internals.js`, which leads to error `Could not find module ember-htmlbars/keywords/view` on ember 2.8.0. 
Application then doesn't load.

ember: 2.8.0-beta.1
ember-cli: 2.8.0-beta.1

**Comment by vlascik** [comment]
I see the fix is already on master, nevermind.

**Comment by ef4** [comment]
Yes, just got fixed on master. But thanks for the report!

**Comment by jbailey4** [comment]
@ef4 we could an official release with this fix go out?

**Comment by blimmer** [comment]
@ef4 this breaks my app against 2.8.x - can we get an official release?

**Comment by ef4** [comment]
Released 0.25.0! Thanks everyone.
