### ISSUE TITLE
`else if` incorrectly hiding oldElement on animation start

### ISSUE THREAD

**Issue by catc** [ember-animation/liquid-fire#490]
If you have the following layout:
```
{{#liquid-if (eq prop 'someVal') }}
     ...
{{else if (eq prop 'someOtherVal'}}
     ...
{{/liquid-if}}
```
When transitioning from `someOtherVal` to `someVal`, the `this.oldElement` is instantly hidden from view when animation initiates.

Reproduced issue at https://ember-twiddle.com/803b3eabcd3c037b8aef2fecf9457bcd?numColumns=3&openFiles=styles.app.css%2Ctemplates.application.hbs%2Ccontrollers.application.js

**Comment by ef4** [comment]
I think the problem is that the second `if` is a plain old ember `if`, not a `liquid-if`. We have no way of telling it not to rerender immediately.

The best way to animate this is:

```hbs
{{#liquid-bind prop as |currentProp|}}
  {{#if (eq currentProp 'someVal')}}
    ...
  {{else if (eq currentProp 'someOtherVal')}}
    ...
   {{/if}}
{{/liquid-bind}}
```

**Comment by buschtoens** [comment]
Referencing #150.
