### ISSUE TITLE
ember-canary is broken on CI

### ISSUE THREAD

**Issue by kellyselden** [ember-animation/liquid-fire#492]
haven't dug into why yet.

https://travis-ci.org/ember-animation/liquid-fire/builds/157163908

**Comment by ef4** [comment]
I am working on the [glimmer2](https://github.com/ember-animation/liquid-fire/tree/glimmer2) branch. I have the full test suite passing against canary there, but need to do a little packaging work before it's merge-able to master.

**Comment by kellyselden** [comment]
@ef4 Understandable. Would you feel comfortable merging unrelated PRs like #491 with a broken canary? Or should we first make canary an acceptable failure for the time being?

**Comment by ef4** [comment]
Marked canary as allowed to fail and restarted travis.

**Comment by ef4** [comment]
(for #491, meant to comment there)

**Comment by rwjblue** [comment]
Likely should be closed in favor of https://github.com/ember-animation/liquid-fire/issues/498 (since I believe glimmer2 compat is the reason for this initially).

**Comment by kellyselden** [comment]
Agreed
