### ISSUE TITLE
Error with Ember 2.8 (attributeBindings on tag-less component: liquid-if)

### ISSUE THREAD

**Issue by deepflame** [ember-animation/liquid-fire#500]
Hi everyone,

experiencing the following error with liquid-fire 0.25 and Ember 2.8 after upgrade:

    ember.debug.js:6778 Uncaught Error: Assertion Failed: 
    You cannot use `attributeBindings` on a tag-less component: <awesome-app@component:liquid-if::ember1420>

Installed everything afresh again and still the issue. Anyone experiencing the same?

(this is the same for `liquid-bind` and `liquid-if`)

**Comment by netes** [comment]
Confirmed, I've got the same issue when using Ember 2.8.

**Comment by ef4** [comment]
Can somebody share a reproduction? The test suite passes using liquid-fire 0.25 and Ember 2.8, and we don't make any direct use of `attributeBindings`. Perhaps

**Comment by kasunvp** [comment]
we have the same issue. we use https://github.com/simplabs/ember-test-selectors for testing.

e.g: an integration test for the component `custom-sort`  
```
test('should render the component', function(assert) {
  this.on('updateSortParams', function(data) {
    this.set('data', data);
  });
  this.render(hbs`{{custom-sort
    data-test-selector='custom-sort'
    updateSortParams=(action 'updateSortParams')
  }}`);
  assert.equal(this.$(testSelector('selector', 'custom-sort')).length, 1, 'should have the component rendered');
});
```

**Comment by netes** [comment]
I only installed Ember 2.8 and the problem showed up, so there are no particular reproduction steps.

**Comment by ef4** [comment]
> I only installed Ember 2.8 and the problem showed up, so there are no particular reproduction steps.

That is not enough detail to allow me to help. If I create a brand new ember app using ember 2.8 and liquid-fire 0.25.0 (or 0.26.1, which is now latest), and add a liquid-if, I don't get this error.

**Comment by ef4** [comment]
Also, as a random guess please check the second BREAKING change [in the 0.25.0 notes](https://github.com/ember-animation/liquid-fire/blob/master/CHANGELOG.md#0250) and see if it applies to you.

**Comment by oscarni** [comment]
Got the exact same issue due to another addon which had an initalizer which added an attributeBinding to all my components without my direct knowledge. It made ember throw this error for all tagless components in my project. It might be worth investigating in your case if a brand new ember app does not throw this error.

In my case it was `ember-hammertime` adding some bindings, it's fixed now in master, just waiting for the new release.

**Comment by ef4** [comment]
Thanks @oscarni, that is helpful. Liquid fire uses tagless components, so any addon that does that would cause the this problem.

**Comment by deepflame** [comment]
Thanks @oscarni . This was actually also the case for me.

Issue: https://github.com/runspired/ember-hammertime/issues/19
