### ISSUE TITLE
scrollThen Error: window.$.Velocity is not a function

### ISSUE THREAD

**Issue by The-Don-Himself** [ember-animation/liquid-fire#508]
First, awesome library, made me throw animate.css out the window, thanks!

I kept getting this issue when using scrollThen and only when using scrollThen

TypeError: window.$.Velocity is not a function at Object.exports.default (/assets/vendor.js:110215:23) at /assets/vendor.js:106162:63 at Object.initializePromise (/assets/vendor.js:62202:7) at new Promise (/assets/vendor.js:63797:21) at Action.run (/assets/vendor.js:106161:16) at RunningTransition._invokeAnimation (/assets/vendor.js:108119:31) at RunningTransition.run (/assets/vendor.js:108094:33) at Class._transition (/assets/vendor.js:106844:18) at Class.childDidRender (/assets/vendor.js:106873:14) at Class.send (/assets/vendor.js:53071:35)

Current hack was to change 
````
    return window.$.Velocity(el, 'scroll', options).then(() => {
      nextTransition.apply(this, rest);
    });
````
to
````
    return Ember.$.Velocity(el, 'scroll', options).then(() => {
      nextTransition.apply(this, rest);
    });
````

**Comment by ef4** [comment]
We recently [merged a change](https://github.com/ember-animation/liquid-fire/pull/507) that ensures there is always a module shim for velocity.  So the fix can be:

```js
import velocity from 'velocity';
return velocity(el, 'scroll', options).then(() => {
      nextTransition.apply(this, rest);
});
```

**Comment by The-Don-Himself** [comment]
Ok thanks @ef4, closing the issue then.
