### ISSUE TITLE
not triggered when transitioning to same route

### ISSUE THREAD

**Issue by bjerh** [ember-animation/liquid-fire#509]
I have my router roughly setup as such:
```
Router.map(function() {
  this.route('index', { path: "" }, function() {
    this.route('page', {path: "/:slug"});
  });
});
```

When transitioning from say _/page-one_ to _/page-two_ the transition in my _transitions.js_ doesn't fire.

My _transitions.js_ file is currently looking like this. I have tried supplying a _toRoute_+_fromRoute_ and a _withingRoute_ with no success. :(

```
export default function () {
	this.transition(
		this.debug(),
		this.use("fade")
	)
}
```

Nothing is debugged when going from route _index.page_ to _index.page_. Otherwise going from a route different from _index.page_ the usual _[liquid-fire rule 0] matched_ is logged.

**Comment by ef4** [comment]
That is because Ember itself doesn't do a route transition in that case, so outlets don't see anything. All that changes in the current model.

Your best option is to `liquid-bind` the model itself, like

```hbs
{{#liquid-bind model as |currentModel|}}
  {{!- the rest of your template goes in here, using "currentModel" instead of "model" }}
{{/liquid-bind}}
```

**Comment by bjerh** [comment]
Figured something like that'd be the case. Thanks a bunch for your help. :-)
