### ISSUE TITLE
Doesn't work in engines

### ISSUE THREAD

**Issue by knownasilya** [ember-animation/liquid-fire#523]
I think @nathanhammond said that `this.import` needs to be used otherwise the css doesn't get added and the build errors.

**Comment by nathanhammond** [comment]
@knownasilya You can modify just one function, polyfill `_findHost` and then go from there:

https://github.com/ember-animation/liquid-fire/blob/08c757d06eaf219cde8a8710a465476650d02957/index.js#L87

Can you take a swing at a PR?

**Comment by knownasilya** [comment]
So just add it (https://github.com/ember-cli/ember-cli/blob/5d64cfbf1276cf1e3eb88761df4546c891b5efa6/lib/models/addon.js#L387) if it's not there? Sure I can PR it.

**Comment by Leooo** [comment]
@knownasilya is LF working with ember-engines for you now? Can't manage to make it work even after your PR: `Error: Compile Error: liquid-outlet is not a helper` thanks

**Comment by knownasilya** [comment]
Make sure to add it as a dependency to you engine.

**Comment by Leooo** [comment]
I was sure I already tried that, but I didn't! Thanks it's working when added into `dependency` folder.
