### ISSUE TITLE
velocity.js seems not be shimmed correctly

### ISSUE THREAD

**Issue by nightire** [ember-animation/liquid-fire#525]
I'm working on an addon, use `ember install liquid-fire` and prepare a demo follow the documentation, then I got this error:

![2016-11-22 7 47 50](https://cloud.githubusercontent.com/assets/1104018/20522749/de9a79b4-b0ec-11e6-8bef-f28ae9f22927.png)

After a little debugging (includes read related issue: #519 and pr: #524), I've found here:

![2016-11-22 7 47 26](https://cloud.githubusercontent.com/assets/1104018/20522798/18de5c9e-b0ed-11e6-8f88-c3b02e8de7b1.png)

Seems `_velocity['default']` is a promise instead an object, so `.CSS` property can not be access.

I can see `vendor/velocity/velocity.js` has been imported through developer tools source panel, but neither `window.Velocity` and `Ember.$.Velocity` existed.

Don't know where gone wrong, any suggestions?

**Comment by Cryrivers** [comment]
Downgrading to Ember CLI 2.8 solved my problem.

**Comment by nightire** [comment]
@Cryrivers Ye, I knew, thanks. I should've mention it is related for 2.9.

**Comment by ef4** [comment]
I think this is fixed in 0.26.5, please give it a try.

**Comment by mnoble01** [comment]
@ef4 I'm getting this same issue with 0.27.3 when using in an engine. 0.27.2 works as expected in the engine.

I do have a liquid-fire dependency in the application using the engine, which you mentioned [here](https://github.com/ember-animation/liquid-fire/issues/519#issuecomment-256861031).
