### ISSUE TITLE
prevent default styles on oldElement

### ISSUE THREAD

**Issue by skaterdav85** [ember-animation/liquid-fire#532]
Is there a way to prevent default styles from being applied to `oldElement`? I was able to do it in my custom transition like this: `this.oldElement.removeAttr('style')`. Just wasn't sure if this was the best way. Thanks!

**Comment by ef4** [comment]
Do you mean disabling certain styles while it is animating? One option for that is that there is a `liquid-animating` class that appears during animation that you can target with different rules.

**Comment by skaterdav85** [comment]
I'm using `liquid-outlet` and during the transition, the `liquid-outlet` element has the `liquid-animating` class. The outlet has 2 children, one of which is the `oldElement` and styles are applied via the style attribute:

```
<div id="ember1275" class="ember-view liquid-child" style="top: 551.188px; left: 0px; width: 1528px; height: 0px; position: absolute;"></div>
```

Basically I don't want those styles applied.

**Comment by ef4** [comment]
It sounds like you may want to avoid the auto-containment stuff. If you set `containerless=true` on `liquid-outlet` I think it will do what you want.

Disentangling containment from animation is one of my priorities going forward.

**Comment by skaterdav85** [comment]
Thank you! This worked!
