### ISSUE TITLE
Error: Could not find module ember-htmlbars/streams/stream

### ISSUE THREAD

**Issue by enrimr** [ember-animation/liquid-fire#535]
Upgrading from 2.9 to 2.10 I got this error when I try to open my app.

**Comment by skaterdav85** [comment]
@enrimr Did you have a resolution for this?

**Comment by ef4** [comment]
@skaterdav85 I think https://github.com/ember-animation/liquid-fire/pull/556 may be related.

**Comment by enrimr** [comment]
@skaterdav85 yes, I had a not upgraded dependency on my project that wasn't compatible with this module. I don't remember what one, but I imagine you could try to rm -rf node_modules && npm install && npm upgrade in order to try to solve it.
