### ISSUE TITLE
Frame timestamps using RAF's high res timestamp can cause dropped frames.

### ISSUE THREAD

**Issue by jrowlingson** [ember-animation/liquid-fire#539]
Velocity now [defaults](https://github.com/julianshapiro/velocity/commit/130d2e6abe290c8d200eeae13e241607151fc9d4) (https://github.com/julianshapiro/velocity/issues/684) frame timestamps to use [RAF's](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) high resolution timestamp. 

This was previously ignored for the following reason:

> We ignore RAF's high resolution timestamp since it can be significantly offset when the browser is under high stress; we opt for choppiness over allowing the browser to drop huge chunks of frames.

So, the issue of dropped frames still remains for scenarios where the browser is under load. Defaulting RAF can cause existing animations to break so this behavior really should be opt-in.

**Comment by ef4** [comment]
This seems good to me since it is maintaining the classic behavior that users of liquid-fire had come to expect from earlier velocity versions.
