### ISSUE TITLE
Glimmer 2: link-to with implicit parameter crashed ember while transitioning away

### ISSUE THREAD

**Issue by Bernhard---H** [ember-animation/liquid-fire#545]
If I use implicit arguments of the link-to helper within a transition, everything seems to break while transitioning away from that template. 

Note: This bug requires Glimmer 2 or Ember 2.10.0 to work 😃 (no bug for older ember versions)

Excample:
``` javascript
Router.map(function() {
  this.route('post', { path: '/post/:post_id' }, function() {
    this.route('comment', { path: 'commment/:comment_id' });
  });
});
```

implicit link-to argument:
``` hbs
{{#link-to 'post.comment' comment}}
    {{comment.text}}
{{/link-to}}
```
explicit link-to argument:
``` hbs
{{#link-to 'post.comment' post comment}}
    {{comment.text}}
{{/link-to}}
```

I created an [ember twiddle](https://canary.ember-twiddle.com/6fc74237ce487710d9b7a686aa4f43d2) to reproduce the bug:

1. click "post 1 title"
2. click "list of posts"
3. everything breaks:
    - assertion error in the console
    - two pages are rendered into each other

## the result:
assertion error in the browser console:
> Error: Assertion Failed: You attempted to define a `{{link-to "post.comment"}}` but did not pass the parameters required for generating its dynamic segments. You must provide param `post_id` to `generate`.

render error - the `from` and `to` pages are overlapping:
> ![render-bug](https://cloud.githubusercontent.com/assets/7544252/22054690/2f5fe000-dd57-11e6-8577-5e1e5fdd79f6.jpg)

**Comment by ef4** [comment]
Thanks for the bug report. This problem is being tracked here:

https://github.com/ember-animation/liquid-fire/issues/347

I think perhaps you didn't find that issue because it had an unhelpful title, which I just updated.

The failure mode looks different on different Ember versions, but implicit parameters to link-to don't work reliably in any Ember version during animations.
