### ISSUE TITLE
LiquidFire and Ember Impagination don't work together

### ISSUE THREAD

**Issue by Alonski** [ember-animation/liquid-fire#576]
Hello,
When using `Ember Impagination` and `Liquid Fire` together:
The data is being brought into the store.
However it isn't being displayed in the UI.

When I use `{{outlet}}` and not `{{liquid-outlet}}` everything works.
Here is a repo the demonstrates this issue:
https://github.com/Alonski/EmberImpaginationLiquidFire

**Comment by rwwagner90** [comment]
This seems like something we probably would not want to devote effort to fixing. If you would like to support it, please feel free to open a PR!
