### ISSUE TITLE
Strange transitions between models

### ISSUE THREAD

**Issue by betocantu93** [ember-animation/liquid-fire#590]
Hello, I've been using liquid-fire for a while, and I've faced this issue twice:

When the model for liquid-bind changes, it initially shows/places the new model; then the transition starts and ends up showing the initially placed model, it looks really weird.
Template: 

```
{{#liquid-bind price class="pricing-box-price"}}
  <div class={{class}}>
    <sup class="currency-symbol">{{currency-symbol}}</sup>
    <span class="price">{{price}}</span>
    <sub class="recurrency">/{{recurrency}}</sub>
  </div>
{{/liquid-bind}}
```

Transitions.js

 ```
 this.transition(
    this.hasClass('pricing-box-price'),
    this.use('fade')
  );
```

Another scenario is tabs, if I want to slide smoothly between tabs with liquid-fire, weird enough it first shows the tab I'm transitioning, then the animation begins... Maybe it's dumb and I'm missing something obvious.

```

{{liquid-bind activeTab class="tab-container"}}
  {{component activeTabName}}
{{/liquid-bind}}

this.transition(
    this.hasClass('tab-container'),
    this.use('toRight')
    this.reverse('toLeft')
  );

```
Thanks in advance for the help

**Comment by ef4** [comment]
There is a simple fix. Change your first example to:

```
{{#liquid-bind price class="pricing-box-price" as |currentPrice|}}
  <div class={{class}}>
    <sup class="currency-symbol">{{currency-symbol}}</sup>
    <span class="price">{{currentPrice}}</span>
    <sub class="recurrency">/{{recurrency}}</sub>
  </div>
{{/liquid-bind}}
```
This allows `liquid-bind` to control the value for you. If you try to use the value directly instead, we have no way of preventing it from changing faster than the animation.

**Comment by betocantu93** [comment]
Thanks @ef4, it worked!
