### ISSUE TITLE
transition between a route and a brother route's index: discrepancy in calculation of biggestSize vs actual transition

### ISSUE THREAD

**Issue by Leooo** [ember-animation/liquid-fire#594]
So Maybe you would ask me to replicate, but I will write something I noticed that looks like a bug:
* Transitioning between route1 and route2.index (route1 and route2 are same level routes) using a `toUp` transition.
* route2.index has a template height of, say, 600px
* When calculating [biggestSize](https://github.com/ember-animation/liquid-fire/blob/master/addon/transitions/move-over.js#L43), the height of the template in route2.index is computed (this.newElement actually displays the index content).
* When doing the `toUp` transition, on the other hand, the newElement being displayed doesn't include the content of the outlet. So transition is off by 600px (large white space on top of the new template when starting the new transition).

**Comment by ef4** [comment]
I tried to reproduce this but could not. I suspect a CSS issue. If you share a working reproduction I can look closer.

**Comment by winne42** [comment]
@Leooo anything new regarding this issue? Can the issue be closed?

**Comment by Leooo** [comment]
@winne42 closing as old issue and I haven't been able to share a working reproduction at the time
