### ISSUE TITLE
error: getViewBounds not a function

### ISSUE THREAD

**Issue by brittshroyer** [ember-animation/liquid-fire#596]
When trying to implement an animation using the {{liquid-if}} handlebars, I'm getting the following error: getViewBounds is not a function. My app is using Ember version 2.7.3 and liquid-fire version 0.29.1.  

Is this a compatibility issue? Thanks.

**Comment by brittshroyer** [comment]
Got rid of the error after downgrading to liquid-fire v 0.26.1

**Comment by ef4** [comment]
That is surprising, we test liquid-fire in CI against both Ember 2.4 and 2.8 (since those are both LTS releases). It works on both of those. Perhaps there was a short-lived problem with 2.7.
