### ISSUE TITLE
Attempted to call .send() with the action 'afterTransition' on the destroyed object liquid-container

### ISSUE THREAD

**Issue by thagul** [ember-animation/liquid-fire#616]
After upgrading my application to ember.js v3.2.0, I see some tests failing with the error `Attempted to call .send() with the action 'afterTransition' on the destroyed object liquid-container`.

I've tried also to upgrade liquid-fire to ember.js 3.2.0 and the same error occurs

```
not ok 190 Chrome 66.0 - Global error: Uncaught Error: Assertion Failed: Attempted to call .send() with the action 'afterTransition' on the destroyed object '<dummy@component:liquid-container::ember4449>'. at http://localhost:7357/assets/vendor.js, line 52555
    ---
        Log: |
            { type: 'error',
              text: 'Uncaught Error: Assertion Failed: Attempted to call .send() with the action \'afterTransition\' on the destroyed object \'<dummy@component:liquid-container::ember4449>\'. at http://localhost:7357/assets/vendor.js, line 52555\n' }
    ...
not ok 191 Chrome 66.0 - Integration: liquid-outlet: it should support `use` option
    ---
        actual: >
            null
        stack: >
            http://localhost:7357/assets/vendor.js:52555
        message: >
            Uncaught Error: Assertion Failed: Attempted to call .send() with the action 'afterTransition' on the destroyed object '<dummy@component:liquid-container::ember4449>'.
        Log: |
    ...
``` 

I suppose that it's due to https://github.com/emberjs/ember.js/pull/16387

**Comment by john-griffin** [comment]
Also just hit this.

**Comment by john-griffin** [comment]
I was able to get around this problem by making sure the project had `0.7.25` of `@ember/test-helpers`. Our project uses yarn and was locked to an earlier version that does not play nicely with ember `2.3`. So I removed the relevant lines from the lock file and regenerated. 

I have submitted a PR to `ember-qunit` to resolve this https://github.com/emberjs/ember-qunit/pull/331

@thagul are you able to confirm this fixes things for you?

**Comment by thagul** [comment]
I'm using ember 3.2 not 2.3, but I confirm that updating test-helpers to 0.7.25 solves the issue.

**Comment by john-griffin** [comment]
Sorry I meant `3.2` (have edited above), thanks for confirming, can you please close the issue?

**Comment by thagul** [comment]
Yes, sure.
See https://github.com/ember-animation/liquid-fire/issues/616#issuecomment-402844873 for solution

**Comment by mike-north** [comment]
Can we 
1) reopen this so developers can find this as they attempt to upgrade
2) detect incompatible (or insufficient?) versions of `@ember/test-helpers` and provide some sort of helpful feedback
