### ISSUE TITLE
Issue with transitions.js and liquid-if using containerless?

### ISSUE THREAD

**Issue by edeis53** [ember-animation/liquid-fire#624]
DOM targeting does not appear to work with liquid-if while using containerless=true. Is this expected behaviour?

**Using the following:**
```
<div id="parent">
{{#liquid-if showMenu enableGrowth=false containerless=true class="test"}}
</div>
```

**None of the following transitions are matched:**
  ```
  this.transition(
    this.hasClass('test'),
    this.use('crossFade')
  );

  this.transition(
    this.matchSelector('.test'),
    this.use('toUp')
  );
  
  this.transition(
    this.childOf('#parent'),
    this.use('toLeft')
  );
```

The only way to have a transition is to define using "use"
`{{#liquid-if showMenu enableGrowth=false containerless=true use="crossFade"}}`

or make a generic one that applies to all.
```
  this.transition(
    this.use('toUp', {duration}),
    this.reverse('toUp', {duration}),
  );
```

**Comment by ef4** [comment]
I'm pretty sure it's possible to use these rules with containerless, but containerless changes the DOM structure such that the CSS selectors need to be different.

If you add debug logging to your rule, it will console.log which Element it's testing so you can check:

```
this.transition(
  this.childOf('#parent'),
  this.use('toLeft'),
  this.debug()
);
```
