### ISSUE TITLE
Is JQuery needed?

### ISSUE THREAD

**Issue by devotox** [ember-animation/liquid-fire#633]
With Ember 3.X Jquery has been deprecated and removed. Is there a path to take to remove all Jquery usage?

**Comment by ef4** [comment]
There is a path. My intention is to make liquid-fire depend on ember-animated, and ember-animated has been designed to not need jQuery.

But this is going to be a breaking change, because we currently expose jQuery in the public API for how transitions get defined.

**Comment by ef4** [comment]
I should also clarify, jQuery is **not** deprecated in Ember 3.x. There's no plan to stop supporting it.

The only thing that's deprecated is having jQuery magically added to your app. Now you'll need to explicitly ask for it.

**Comment by devotox** [comment]
@ef4 yup totally correct that is what I meant not deprecated but too lazy to right out the full sentence. Typical developer ay?

When you do have a set of plans for how you are going to move forward moving over to ember-animated and you would love to break up the work. I would gladly take some on
