### ISSUE TITLE
versionCompatibility ? 

### ISSUE THREAD

**Issue by ctjhoa** [ember-animation/liquid-fire#634]
README says:
> The oldest supported version is listed in `versionCompatibility` in `package.json`, and in CI we test every minor release since then, through beta and canary.

However there is no `versionCompatibility` field in `package.json`.
Should we remove this section and rely on [Ember Compatibility Table](https://github.com/ember-animation/liquid-fire#ember-compatibility-table)?

**Comment by ef4** [comment]
Yes, thanks, that's out of date.

The oldest supported version in current releases is still 1.13.
