### ISSUE TITLE
TypeError: Ember.$ is not a function

### ISSUE THREAD

**Issue by ahemed-haneen** [ember-animation/liquid-fire#645]
> Uncaught (in promise) TypeError: Ember.$ is not a function
>     at Class.afterChildInsertion (liquid-container.js:72)
>     at Class.send (action_support.js:18)
>     at Class.superWrapper [as send] (index.js:367)
>     at Class.notifyContainer (liquid-versions.js:111)
>     at Class._transition (liquid-versions.js:69)
>     at Class.childDidRender (liquid-versions.js:120)
>     at Backburner._join (backburner.js:995)
>     at Backburner.join (backburner.js:760)
>     at join (index.js:179)
>     at index.js:7392
> 

This is the error thats being shown when i try to use liquid-outlet or liquid-if. is there a solution for this?
im on ember 3.14 octane edition. will that be an issue?

**Comment by ef4** [comment]
liquid-fire requires jQuery. You can still use jQuery with Ember Octane, but it's no longer included by default, so it needs to be added explicitly.

**Comment by jrjohnson** [comment]
Should [@ember/jquery](https://github.com/ember-animation/liquid-fire/blob/master/package.json#L28) be a direct dependency then?

**Comment by rwwagner90** [comment]
@ef4 is the jQuery usage extensive? Should we try to remove it?

**Comment by ef4** [comment]
It's part of liquid-fire's public API. So since we need a pretty breaking release to remove it, I was assuming we would do it simultaneously with porting ember-animated into liquid-fire as the animation engine.

**Comment by Alonski** [comment]
@ef4 Just can into this 😃 
I wanted to use Ember Animated but couldn't figure out how to do route transitions.
Could we remove jQuery. Cut a major/minor. And then do the ember-animated work?

**Comment by jherdman** [comment]
I've been playing whack-a-mole chopping out jQuery where possible, but it's kind of grueling. I know Octane is complaining about `Ember.$` but I honestly can't find any instance of it. Is it just that `@ember/jquery` needs to be a direct dependency?

**Comment by jherdman** [comment]
Possibly resolved by #648

**Comment by ef4** [comment]
People who think they need to drop jquery just to use octane are mistaken. See https://github.com/ember-animation/liquid-fire/pull/648#issuecomment-572211989

**Comment by Alonski** [comment]
Still would be nice to remove jquery usage if not 100% essential. Which it seems it isn't.

**Comment by ef4** [comment]
We get that for free by porting to ember-animated, plus we get all of ember-animated, and then people with custom transitions only need to rewrite them once, instead of twice.

**Comment by rwwagner90** [comment]
If the ember-animated conversion might be awhile though, removing jQuery first could be nice.

**Comment by toovy** [comment]
For simple ppl like me who want to use Octane but don't care about jQuery, you can read about installing jQuery in Octane here: https://guides.emberjs.com/release/configuring-ember/optional-features/

```
ember feature:enable jquery-integration
ember install @ember/jquery
```

It would be super awesome to have ember-animated integrated into liquid-fire. Really looking forward! 👍

**Comment by mpanic** [comment]
Ember now throws deprecation warning:

`DEPRECATION: The integration of jQuery into Ember has been deprecated and will be removed with Ember 4.0. You can either opt-out of using jQuery, or install the `@ember/jquery` addon to provide the jQuery integration. Please consult the deprecation guide for further details: https://emberjs.com/deprecations/v3.x#toc_jquery-apis`

Does this mean that `liquid-fire` won't work with the release of Ember 4.0?

What's the migration/support plan?

**Comment by gedaiu** [comment]
I tried to get rid of jQuery from my project, but unfortunately `liquid-fire` is still using it... Are there any plans to remove jQuery from liquid fire, or should I try to remove liquid fire for now?

**Comment by mkszepp** [comment]
Maybe somone is interested, because it should also fix this error.
I have opend a Issue + PR. With this changes all internal `jquery` usages were removed with native js, so there is not anymore necessary to add `jquery` as dependency.

Additional info on https://github.com/ember-animation/liquid-fire/issues/673

**Comment by mkszepp** [comment]
with `v0.35.0` there is now possible to use `liquid-fire` without `jquery` as dependency
