### ISSUE TITLE
Transition to loading template (application-loading.hbs)

### ISSUE THREAD

**Issue by claronz** [ember-animation/liquid-fire#647]
I'm building an application which uses fade animation transition to all pages, everything works as expected except where the loading page is displayed.
What I want it to be is 
page 1 > **fade transition** > application-loading.hbs > **fade transition** > page 2
What i got is
page 1 > application-loading.hbs > page 2
which has no fade transition at all
fade transition works fine on all pages which don't need application-loading.hbs to be loaded

Note:
I have replaced the {{outlet}} to {{liquid-outlet}} in my application.hbs

the content of my transition.js
![image](https://user-images.githubusercontent.com/59242157/71457100-00999480-27cf-11ea-8230-7bbf5f898106.png)

**Comment by ef4** [comment]
You can write rules that will match the `page 1 -> loading` and `loading -> page 2` transitions, but they're different transitions from liquid-fire's perspective, and each needs to match a rule.

If you put `this.debug()` inside `this.transition(...)` it will print what transitions are happening so you can figure out exactly what names to use.

**Comment by claronz** [comment]
I solved the problem by making "loading" as a route, i ran "ember g route loading" (I manually created loading.hbs before so the transition does not work) and now everything works as I want it to be. but a new problem occurs where my transiton does not work on nested routes, I might open a new issue on that later.
