### ISSUE TITLE
liquid-outlet not working with ember stack 3.13 and onwwards

### ISSUE THREAD

**Issue by fakalit** [ember-animation/liquid-fire#650]
Hi there.

Was trying my hand at the sample route transition descibed at https://ember-animation.github.io/liquid-fire/cookbook but it seems like it's not working with ember stack 3.13 onwards.

I tried running the following in various ember cli versions.

```
$ npm install -g ember-cli@3.13
$ ember new liquid-sandbox
$ cd liquid-sandbox
$ ember install liquid-fire
$ ember g route routeone
$ ember g route routetwo
$ npm start
```
And pasted the following code in the corresponding files.

application.hbs
```
<nav>
  <ul>
    <li>{{#link-to "routeone"}}one{{/link-to}}</li>
    <li>{{#link-to "routetwo"}}two{{/link-to}}</li>
  </ul>
</nav>

<main>
  {{liquid-outlet}}
</main>
```
routeone.hbs
`ONE`

routetwo.hbs
`TWO`

transition.js
```
export default function(){
  this.transition(
    this.fromRoute('routeone'),
    this.toRoute('routetwo'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
}
```
Everything works as expected with if I do the exact same as above with ember 3.12 and below, but liquid-outlet stops displaying anything 3.13 and onwards. Transitions do not work and liquid-child div is styled with a "visibility: hidden".

Did support for this library drop in favour of ember animated @ef4?

**Comment by sebastianhelbig** [comment]
Same problem for me.

**Comment by colenso** [comment]
Any movement on a solution for this issue? I updated a project that I was working on to ember 3.21 and came across this issue.

**Comment by knownasilya** [comment]
Just noticed this after an upgrade.

**Comment by GeekSMN** [comment]
Any status on this? I just ran into it as well

**Comment by GeekSMN** [comment]
I have recently upgraded my project from a 2.x version of Ember to 3.x and believe I am seeing this problem but with liquid-bind, however downgrading to 3.12 does not seem to solve the issue. Any suggestions?

**Comment by rwwagner90** [comment]
Is this still occurring on the latest release?

**Comment by rwwagner90** [comment]
All tests are passing, even through beta and canary now, so we think this is fixed. I am going to close for now, and if it is not fixed, please let us know!
