### ISSUE TITLE
State of this project

### ISSUE THREAD

**Issue by sandstrom** [ember-animation/liquid-fire#655]
Just curious, what's the state of this project?

For example:

- Does it work with recent versions of Ember (https://github.com/ember-animation/liquid-fire/issues/650)?
- Is there a lot of work to keep this project in step with Ember, or are there mostly minor adjustments needed to keep it in lock step? 
- Do you need help maintaining it? (for example cleaning out old issues, or building in new functionality)
- Are there any upcoming changes to Ember (deprecations around outlets, new Embroider, etc) that will require a larger refactor on liquid fire?

Also, thanks for an awesome project! 🏅 It's very useful for mobile apps, where it's common to animate route transitions.

**Comment by ef4** [comment]
My open source time is all going into embroider right now, so help would be welcome. No major changes are needed to just to keep liquid-fire working.

It does depend on JQuery and expose jQuery within it's public API, and lots of apps would prefer to stop needing jQuery, but jQuery also continues to work fine with all Ember versions (it's just optional now where it used to be required by ember).

**Comment by rwwagner90** [comment]
liquid-fire is incompatible with embroider and Ember canary / Ember 4.0 currently. I'm happy to help where I can, and I opened a PR attempting to remove Ember globals, https://github.com/ember-animation/liquid-fire/pull/657 but once I tried using it, I started getting some failures on Ember < 3.24, so I am not sure if I did things correctly.

@ef4 would it be possible for you to take a look and offer some guidance? If we can identify the issues for embroider and Ember 4 and some possible paths toward a fix, I am happy to take a stab at implementing them. It also seemed like tests were not running on the PR. Should we perhaps migrate to GitHub actions?

**Comment by ef4** [comment]
Thanks @rwwagner90. Yes, the first step we need someone to help with is to setup github actions. This repo was on Travis and that's not running anymore.  There will probably be test failures on newer ember releases, those need to be triaged.

**Comment by rwwagner90** [comment]
@ef4 here is a PR for GitHub actions https://github.com/ember-animation/liquid-fire/pull/658

**Comment by rwwagner90** [comment]
@sandstrom I believe everything is fixed and working with latest Ember now, so I am going to close this.
