### ISSUE TITLE
Discrepancy between changelog and compatibility table

### ISSUE THREAD

**Issue by jacobq** [ember-animation/liquid-fire#671]
Compatibility table should be updated to cover breaking change in v0.34.0

https://github.com/ember-animation/liquid-fire/blob/master/CHANGELOG.md
> 0.34.0 (2022-01-19)
>    BREAKING: oldest supported Ember is now 3.16
>    COMPAT: full compatibility with Ember 4.1 and Embroider by @rwwagner90

https://github.com/ember-animation/liquid-fire/wiki/Compatibility-Table,-Old-Versions
> <html>
<body>

Ember Version | Liquid Fire Release
-- | --
2.12 and newer | latest

</body>
</html>

**Comment by mkszepp** [comment]
compatibility table was added in README https://github.com/ember-animation/liquid-fire#ember-compatibility-table & wiki removed
