### ISSUE TITLE
"Cannot read properties of null" issue when using "explode" with fixed-position element after upgrading to 0.35.0

### ISSUE THREAD

**Issue by pzubar** [ember-animation/liquid-fire#678]
Hello! 
It seems like there is a little regression in the `0.35.0` version. In this [line](https://github.com/ember-animation/liquid-fire/blob/983d00f0103179f608b5f1402d4852c0ee6747b7/addon/transitions/explode.js#LL121C39-L121C47) just `newChild.offsetParent` is used. If the `newChild` has `position: fixed`, the `offsetParent` will be `null`.
That means the following error will be thrown:
`Cannot read properties of null (reading 'getBoundingClientRect')`

However, in the `jQuery` version `newChild.offsetParent()` was resolved to the `html` element (so that the offset was `{ top: 0, left: 0 }` and worked fine). Is it possible to add the fallback there? Thanks!

**Comment by mkszepp** [comment]
@pzubar thanks for the bug report. i have provided a fix https://github.com/ember-animation/liquid-fire/pull/679. can you check, if the fix soved your problem?

**Comment by pzubar** [comment]
@mkszepp thanks for the fix, I think it should work fine!

**Comment by pzubar** [comment]
The most recent updates in the main branch will require `ember-source@>=4`. Could you please release this fix separately before the "major" update, please (like `0.35.1`)? It would be so great 🙏

**Comment by mkszepp** [comment]
@pzubar i have backported and released `v0.35.1.`

**Comment by pzubar** [comment]
Thanks @mkszepp!
