### ISSUE TITLE
jQuery removal in 0.35 breaks liquid-fire/transitions/move-over, maybe others?

### ISSUE THREAD

**Issue by apellerano-pw** [ember-animation/liquid-fire#686]
The jQuery version was doing `context.newElement.parent().css('width')` which was evaluating for me to e.g. `'100px'`.

The vanilla js version does `context.newElement.parentElement.style['width']` which evaluates in the same situation to `''` empty string.

AFAICT `parent()` is equivalent to `parentElement`.

The issue is that `css('width')` is not equivalent to `style['width']`. A better match would be `getComputedStyle(context.newElement.parentElement)['width']`

There is quite a lot of `css()` usage replaced in https://github.com/ember-animation/liquid-fire/pull/674 so I'm not sure how deep the issue is; the codebase I work with only uses a couple of transitions.

Workaround is to downgrade to 0.34

**Comment by mkszepp** [comment]
Thanks for reporting... i have looked all jquery replaced and i think there was only this one wrong... i will make a release in the next minutes (0.36.1)

**Comment by apellerano-pw** [comment]
Oh, that's good! Thank you for checking the other spots and fixing this one!
