### ISSUE TITLE
Predicate seems to now be required in template helpers

### ISSUE THREAD

**Issue by LucasHillDex** [ember-animation/liquid-fire#689]
Previously you could write something like: 
`
{{#liquid-if this.myCondition}}
  Hidden
{{/if}}
`

As of v0.36 it seems you must write:
`
{{#liquid-if predicate=this.myCondition}}
  Hidden
{{/if}}
`

The docs do not reflect this:
https://ember-animation.github.io/liquid-fire/helpers/liquid-if

Is predicate intended to be required (the tests use it that way), or is this unintentional?

**Comment by mkszepp** [comment]
@LucasHillDex thanks for info... i think we need only to publish docs, because we have already updated.

https://github.com/ember-animation/liquid-fire/blob/v0.36.1/docs/app/templates/helpers-documentation/liquid-if.hbs

I will look to find time

**Comment by mkszepp** [comment]
@LucasHillDex Docs are now published... thanks for reporting
