### ISSUE TITLE
Programatically define transitions

### ISSUE THREAD

**Issue by Globegitter** [ember-animation/liquid-fire#95]
Let's say I have transitions from/to routes, so my transitions.js would look like:

``` js
this.transition(
  this.fromRoute('foo'),
  this.toRoute('bar'),
  this.use('toLeft')
);
```

But now I don't want this route to always be `toLeft`, but depending on some user interaction I want this to be right, up, down or whatever.
So is it possible to change/set, for example in a controller the type of animation/transition for a route? This could probably also be extended to the other types of transitions, but routes are the only ones we need for our use case.

**Comment by drewcovi** [comment]
@ef4 I'm looking into a hybrid web/mobile app where transitions at a lower brake point provides an excellent mobile-tailored experience. However they don't make as much sense in a desktop resolution. I'm assuming that the matchSelector would help in this use case?

**Comment by drewcovi** [comment]
disregard. found mediaquery :)
